(function(){
'use strict';
const locations=new Map();let rows=[],map=null,layer=null,loader=null,opened=false,dbLoaded=false,dbLoading=null,dbNote='',dbGroups=new Map();
const $=id=>document.getElementById(id),en=()=>giLanguage()==='en',t=(th,eng)=>en()?eng:th,esc=v=>escapeHtml(String(v??''));
const norm=v=>String(v||'').normalize('NFKC').toLowerCase().replace(/[\s.,()\-_]/g,'');
function parseCoordinates(raw){return String(raw||'').split(/\r?\n/).filter(x=>x.trim()).map(line=>{const m=line.match(/^\s*([+-]?\d+(?:\.\d+)?)\s*,\s*([+-]?\d+(?:\.\d+)?)\s*$/);if(!m)throw Error('Lat/Long: '+line);const lat=+m[1],lng=+m[2];if(lat<-90||lat>90||lng<-180||lng>180)throw Error('พิกัดเกินช่วง: '+line);return {lat,lng}})}
function matchRows(source,names){const index=new Map();for(const name of names){const k=norm(name);index.set(k,[...(index.get(k)||[]),name])}return source.map(r=>{const options=index.get(norm(r.name))||[];return {...r,plant:options.length===1?options[0]:null}})}
function stats(plant,dates){const p=plantMasterData[plant],min=Number($('minIrr').value)||0,max=Number($('maxIrr').value)||99;let count=0,total=0,alarm=0,accepted=0;for(const date of dates){const v=p.dates[date];if(!GiReview.valid(v))continue;count++;total+=v;if(v<min||v>max){if(GiReview.confirmed(giReviewByPlant[plant]?.days?.[date],v))accepted++;else alarm++}}return {count,total,avg:count?total/count:null,alarm,accepted,status:count<dates.length?'NOT_FOUND':alarm?'ABNORMAL':'NORMAL',review:monthlyReviewStatus(plant,reviewMonth(dates))}}
async function loadLocations(){if(dbLoaded)return;if(dbLoading)return dbLoading;dbLoading=(async()=>{const id=new URL(location.href).searchParams.get('project');if(!id){dbNote=t('เปิดผ่านโครงการใน Control Center เพื่อโหลดพิกัดฐานข้อมูล','Open a Control Center project to load database locations');return}const client=SolarCloud.getClient();const {data:project,error:projectError}=await client.from('analysis_projects').select('workspace_id').eq('id',id).single();if(projectError)throw projectError;const results=await Promise.all([client.from('central_project_locations').select('project_id,source_name,source_contract,ordinal,latitude,longitude,central_projects(standard_name),spare_project_catalog(project_name,source_name)').eq('workspace_id',project.workspace_id).order('ordinal'),client.from('central_project_aliases').select('project_id,alias_name').eq('workspace_id',project.workspace_id)]);for(const r of results)if(r.error)throw r.error;const groups=new Map();for(const r of results[0].data||[]){const key=r.project_id||r.source_contract;let g=groups.get(key);if(!g){g={names:new Set([r.source_name,r.central_projects?.standard_name,r.spare_project_catalog?.project_name,r.spare_project_catalog?.source_name].filter(Boolean)),points:[]};groups.set(key,g)}g.points.push({lat:r.latitude,lng:r.longitude})}for(const a of results[1].data||[])groups.get(a.project_id)?.names.add(a.alias_name);dbGroups=groups;const previous=locations.size;bindDatabaseLocations();const matched=locations.size-previous;dbLoaded=true;dbNote=t('โหลดพิกัดจากฐานข้อมูลแล้ว','Database locations loaded')+' · '+matched+' '+t('โครงการที่มีข้อมูล GI ตรงกัน','matching GI projects')})().catch(error=>{dbNote=t('โหลดพิกัดฐานข้อมูลไม่สำเร็จ: ','Unable to load database locations: ')+error.message}).finally(()=>dbLoading=null);return dbLoading}
function loadLeaflet(){if(window.L)return Promise.resolve();if(loader)return loader;loader=new Promise((resolve,reject)=>{const css=document.createElement('link');css.rel='stylesheet';css.href='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css';document.head.append(css);const js=document.createElement('script');js.src='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js';const timer=setTimeout(()=>reject(Error(t('โหลดแผนที่หมดเวลา','Map load timed out'))),15000);js.onload=()=>{clearTimeout(timer);resolve()};js.onerror=()=>{clearTimeout(timer);reject(Error(t('โหลดแผนที่ไม่สำเร็จ','Unable to load map')))};document.head.append(js)}).catch(e=>{loader=null;throw e});return loader}
async function open(){opened=true;labels();await loadLocations();try{await loadLeaflet();if(!opened)return;if(!map){map=L.map('giMapCanvas',{zoomControl:true,preferCanvas:true}).setView([13.3,101],6);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'}).on('tileerror',()=>{$('giMapMessage').textContent=t('ภาพแผนที่บางส่วนโหลดไม่ได้ รายการโครงการยังใช้งานได้','Some map tiles failed; project list remains available')}).addTo(map);layer=L.layerGroup().addTo(map)}map.invalidateSize();render()}catch(e){$('giMapMessage').textContent=e.message}}
function close(){opened=false;if(map){map.remove();map=null;layer=null}}
function labels(){for(const [id,th,eng] of [['giMapImportLabel','เลือกไฟล์พิกัด','Load coordinates'],['giMapFilterLabel','ตัวกรองร่วมกับตาราง','Shared table filters'],['giMapFitLabel','ดูทุกหมุด','Fit projects'],['giMapAddLabel','เพิ่มพิกัด','Add location'],['giMapRetryLabel','ลองแผนที่ใหม่','Retry map']])$(id).textContent=t(th,eng);$('giMapPreview').textContent=dbNote+' · '+t('การเพิ่มหรือเลือก Excel ในหน้านี้เป็น Preview เท่านั้น','Manual additions and Excel selections here are preview only')}
function bindDatabaseLocations(){const candidates=new Map();for(const [key,g] of dbGroups)for(const name of g.names){const k=norm(name);candidates.set(k,new Set([...(candidates.get(k)||[]),key]))}for(const name of Object.keys(plantMasterData)){const keys=candidates.get(norm(name));if(keys?.size===1&&!locations.has(name))locations.set(name,dbGroups.get([...keys][0]).points)}}
function visible(){bindDatabaseLocations();const dates=getFilteredDates(),query=$('giMapSearch').value.trim().toLowerCase();return [...selectedPlants].filter(name=>plantMasterData[name]&&(activeProvinceFilter==='ALL'||plantMasterData[name].province===activeProvinceFilter)&&(!query||name.toLowerCase().includes(query))).map(name=>({name,values:stats(name,dates),points:locations.get(name)||[]})).filter(p=>(activeStatusFilter==='ALL'||p.values.status===activeStatusFilter)&&(activeReviewFilter==='ALL'||p.values.review===activeReviewFilter))}
function detail(p){const dates=getFilteredDates(),v=p.values;return `<strong>${esc(p.name)}</strong><p>${esc(provinceLabel(plantMasterData[p.name].province||'ไม่ระบุ'))} · ${esc(plantMasterData[p.name].capacity)} kWp</p><p>GI ${v.avg===null?'—':v.avg.toFixed(3)} kWh/m²/${t('วัน','day')}</p><p>${esc(dates[0]||'—')} — ${esc(dates.at(-1)||'—')}</p><p>${t('ข้อมูล','Data')} ${v.count}/${dates.length} ${t('วัน','days')} · Alarm ${v.alarm} · ${t('รับรองรายวัน','Accepted days')} ${v.accepted}</p><p>${t('สถานะตรวจรายเดือน','Monthly review')}: ${esc(v.review||'—')}</p><small>${t('ค่าเฉลี่ยรวมค่าที่มีข้อมูลทั้งหมด ไม่ตัด Alarm และไม่เปลี่ยนการคำนวณ PR','Average includes all available values, including alarms; PR calculation unchanged')}</small>`}
function render(){if(!opened)return;labels();const list=visible(),dates=getFilteredDates();$('giMapPeriod').textContent=`${dates[0]||'—'} — ${dates.at(-1)||'—'} · ${dates.length} ${t('วัน','days')}`;$('giMapMessage').textContent=t('ใช้การเลือกโครงการ จังหวัด ช่วงวัน สถานะ และสถานะตรวจเดียวกับตาราง','Uses table plant, province, date, status and review filters');$('giMapList').replaceChildren();if(layer)layer.clearLayers();const groups=new Map();let missing=0;for(const p of list){const btn=document.createElement('button');btn.className='gi-map-row';btn.type='button';btn.innerHTML=`<span>${esc(p.name)}</span><b>${p.values.avg===null?'—':p.values.avg.toFixed(3)}</b><small>${p.points.length?t('มีพิกัด','Located'):t('ไม่มีพิกัด','No location')} · ${p.values.count}/${dates.length}</small>`;btn.onclick=()=>{ $('giMapDetail').innerHTML=detail(p);if(p.points.length&&map)map.setView([p.points[0].lat,p.points[0].lng],13,{animate:false})};$('giMapList').append(btn);if(!p.points.length){missing++;continue}const first=p.points[0],key=first.lat+','+first.lng;groups.set(key,[...(groups.get(key)||[]),p])}if(layer)for(const [key,projects] of groups){const coords=key.split(',').map(Number),v=projects[0].values,color=projects.length>1?'#6366f1':v.avg===null?'#64748b':v.alarm?'#dc2626':v.count<dates.length?'#d97706':'#16a34a';L.circleMarker(coords,{radius:projects.length>1?11:8,color,fillColor:color,fillOpacity:.7,weight:2}).bindTooltip(projects.length>1?`${projects.length} ${t('โครงการ','projects')}`:`${esc(projects[0].name)}: ${v.avg===null?'—':v.avg.toFixed(3)}`).on('click',()=>{$('giMapDetail').replaceChildren();for(const p of projects){const card=document.createElement('div');card.className='gi-map-detail-card';card.innerHTML=detail(p);if(p.points.length>1){const b=document.createElement('button');b.className='btn btn-secondary';b.textContent=t('แสดงจุดย่อย','Show sublocations')+' ('+p.points.length+')';b.onclick=()=>{p.points.slice(1).forEach(point=>L.circleMarker([point.lat,point.lng],{radius:5,color:'#6366f1'}).bindTooltip(esc(p.name)).addTo(layer));map.fitBounds(p.points.map(point=>[point.lat,point.lng]),{maxZoom:16,animate:false})};card.append(b)}$('giMapDetail').append(card)}}).addTo(layer)}$('giMapCount').textContent=`${list.length} ${t('โครงการ','projects')} · ${missing} ${t('ไม่มีพิกัด','unlocated')}`}
function fit(){const points=visible().flatMap(p=>p.points.map(x=>[x.lat,x.lng]));if(map&&points.length)map.fitBounds(points,{padding:[30,30],maxZoom:13,animate:false})}
async function importFile(event){const f=event.target.files[0];if(!f)return;try{await ensureXlsx();const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});const sheet=wb.Sheets['Project List'];if(!sheet)throw Error('ไม่พบ Sheet Project List');const source=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''});const headers=source.shift().map(x=>String(x).replace(/\s+/g,' ').trim());const nameCol=headers.indexOf('Customer Name'),coordCol=headers.indexOf('Lat/Long');if(nameCol<0||coordCol<0)throw Error('ไม่พบ Customer Name / Lat/Long');const seen=new Set();rows=[];for(const r of source){if(!r[nameCol]||!String(r[coordCol]).trim())continue;const key=norm(r[0]);if(seen.has(key))continue;seen.add(key);rows.push({name:String(r[nameCol]).trim(),contract:r[0],points:parseCoordinates(r[coordCol])})}rows=matchRows(rows,Object.keys(plantMasterData));for(const r of rows)if(r.plant)locations.set(r.plant,r.points);mapping();render();fit()}catch(e){await SolarCloud.notice(t('อ่านพิกัดไม่สำเร็จ','Coordinate import failed'),e.message,'danger')}finally{event.target.value=''}}
function mapping(){const box=$('giMapMapping');box.replaceChildren();for(const r of rows.filter(x=>!x.plant)){const div=document.createElement('div');div.className='gi-map-match';const label=document.createElement('label');label.textContent=r.name+' · '+r.contract;const select=document.createElement('select');select.innerHTML=`<option value="">${t('ยังไม่จับคู่ / ข้าม','Unmatched / skip')}</option>`+Object.keys(plantMasterData).sort().map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');select.onchange=()=>{if(!select.value)return;if(locations.has(select.value)&&!confirm(t('โครงการนี้มีพิกัดแล้ว ต้องการแทนที่ในหน้าทดสอบไหม?','Replace existing preview coordinates?')))return;r.plant=select.value;locations.set(r.plant,r.points);mapping();render()};div.append(label,select);box.append(div)}$('giMapMatchCount').textContent=`${rows.filter(r=>r.plant).length}/${rows.length} ${t('รายการมีพิกัดจับคู่แล้ว','located rows matched')}`}
async function add(){const name=$('giMapAddPlant').value,raw=$('giMapAddCoords').value;if(!name)return;try{const points=parseCoordinates(raw);if(!points.length)throw Error(t('กรอก Lat, Long','Enter Lat, Long'));locations.set(name,points);$('giMapAddCoords').value='';render();fit()}catch(e){SolarCloud.notice('Lat/Long',e.message,'warning')}}
function controls(){openFilterModal();const observer=new MutationObserver(()=>{if($('filterModal').style.display==='none'){observer.disconnect();render()}});observer.observe($('filterModal'),{attributes:true,attributeFilter:['style']})}
function setup(){const input=$('giMapFile');input.onchange=importFile;$('giMapSearch').oninput=render;$('giMapAddPlant').innerHTML='<option value="">'+t('เลือกโครงการ','Select project')+'</option>'+Object.keys(plantMasterData).sort().map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('')}
window.GiMap={open:async()=>{setup();await open()},close,render,fit,add,controls,parseCoordinates,matchRows};
})();
