const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),{JSDOM}=require('jsdom'),path=require('path');
const source=fs.readFileSync(path.resolve(__dirname,'../cloud-core.js'),'utf8');
const rooms=new Map();let state={id:'analysisA',analysis_type:'working_day',version:1,user_state:{overrides:{plant:{cap:100}},selectedMonth:'2026-08'}};
function clientFor(user){return {auth:{getSession:async()=>({data:{session:{user:{id:user,email:user+'@example.test'}}}})},channel(topic,options){const key=String(!!options.config.private)+':'+topic,room=rooms.get(key)||new Set();rooms.set(key,room);const c={handlers:[],meta:null,on(type,filter,fn){this.handlers.push({type,filter,fn});return this},subscribe(fn){room.add(this);this.callback=fn;queueMicrotask(()=>fn('SUBSCRIBED'));return this},presenceState(){return Object.fromEntries([...room].filter(x=>x.meta).map((x,i)=>[String(i),[x.meta]]))},async track(meta){this.meta=JSON.parse(JSON.stringify(meta));for(const x of room)for(const h of x.handlers)if(h.type==='presence'&&h.filter.event==='sync')h.fn();},async untrack(){this.meta=null;room.delete(this)},async send(message){for(const x of room)if(x!==this)for(const h of x.handlers)if(h.type===message.type&&h.filter.event===message.event)h.fn({payload:message.payload})}};c.options=options;return c},removeChannel:async c=>c.untrack(),from(){const chain={select:()=>chain,eq:()=>chain,is:()=>chain,single:async()=>({data:JSON.parse(JSON.stringify(state))})};return chain}}}
function setup(user,id,type){const dom=new JSDOM('<input id="edit"><div id="solarCloudModal"><div id="solarCloudModalBox"><h3></h3></div><div id="solarCloudLogs"></div></div><div id="solarCloudStatus"></div><div id="solarCloudDot"></div><button id="solarPresenceButton"></button><span id="solarPresenceCount"></span>',{url:'https://example.test',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,ctx=dom.getInternalVMContext();vm.runInContext(source.replace('  global.SolarCloud={','  global.qa={setup:(p,m,a,c)=>{currentProject=p;currentMembership=m;adapter=a;client=c;lastSharedState=sharedState(p.user_state)},refreshRemoteState,subscribe,pendingPatches,persistFieldPatches,save,markDirty:()=>{dirty=true},info:()=>({remotePending,workspaceConnected,projectConnected,users:presenceUsers,currentProject})};\n  global.SolarCloud={'),ctx);let local={overrides:{plant:{cap:100}},selectedMonth:'2026-09',visibleProjects:['plant']},restores=0;const adapter={capture:()=>({baseData:{records:[]},userState:local}),restore:async(base,next)=>{restores++;local=next},presenceContext:()=>null,onPresence:()=>{}};const client=clientFor(user);w.qa.setup({id,analysis_type:type,version:1,user_state:state.user_state},{workspace_id:'workspace1',role:'editor'},adapter,client);return {dom,w,ctx,client,get local(){return local},get restores(){return restores}}}
(async()=>{const a=setup('userA','analysisA','working_day'),b=setup('userB','analysisB','pr_report');try{await a.w.qa.subscribe();await b.w.qa.subscribe();await new Promise(r=>setTimeout(r,10));assert.equal(a.w.qa.info().users.length,2);assert.equal(b.w.qa.info().users.length,2);assert.ok(rooms.has('true:workspace-online:workspace1'));assert.ok(a.w.qa.info().users.some(u=>u.area==='PR Report'));assert.ok(a.w.qa.info().users.every(u=>!('email' in u)));state={...state,version:2,user_state:{overrides:{plant:{cap:110}},selectedMonth:'2026-07'}};
a.w.document.getElementById('edit').focus();await a.w.qa.refreshRemoteState();assert.equal(a.restores,0);assert.equal(a.w.qa.info().remotePending,true);a.w.document.getElementById('edit').blur();await a.w.qa.refreshRemoteState();assert.equal(a.restores,1);assert.equal(a.local.selectedMonth,'2026-09');assert.equal(a.local.overrides.plant.cap,110);
// A draft created while a remote request is in flight must survive the response.
let resolve;const deferred={select(){return this},eq(){return this},is(){return this},single:()=>new Promise(r=>resolve=r)};const old=a.client.from;a.client.from=()=>deferred;const request=a.w.qa.refreshRemoteState();a.local.overrides.plant.cap=115;resolve({data:{...state,version:3,user_state:{overrides:{plant:{cap:120}}}}});await request;assert.equal(a.restores,1);assert.equal(a.local.overrides.plant.cap,115);assert.equal(a.w.qa.info().remotePending,true);a.client.from=old;
// Explicitly editing a shared field keeps remote refresh deferred.
a.w.qa.markDirty();await a.w.qa.refreshRemoteState();assert.equal(a.restores,1);
// Reconnection status must not claim an online count when both channels are down.
for(const room of rooms.values())for(const c of room)if(c.meta?.userId==='userA')c.callback('CHANNEL_ERROR');assert.equal(a.w.document.getElementById('solarPresenceCount').textContent,'—');
const c=setup('userC','analysisA','working_day');try{let calls=0;c.client.rpc=async()=>{calls++;state={...state,version:4,user_state:{overrides:{plant:{cap:101,note:'remote note'}}}};return {data:{project:JSON.parse(JSON.stringify(state))}}};c.local.overrides.plant.cap=101;await c.w.qa.persistFieldPatches([{path:['overrides','plant','cap'],value:101}]);assert.equal(c.w.qa.pendingPatches().length,0);assert.ok(c.w.SolarCloud.deferredSharedPaths().some(p=>p.includes('note')));assert.equal(c.local.overrides.plant.note,undefined);c.local.overrides.plant.note='my note';await c.w.qa.save();assert.equal(calls,1);assert.ok(c.w.document.getElementById('solarCloudModal').classList.contains('open'));await c.w.SolarCloud.useLatestConflict();assert.equal(c.local.overrides.plant.note,'remote note');assert.equal(c.w.qa.pendingPatches().length,0);assert.equal(c.local.selectedMonth,'2026-09');}finally{c.dom.window.close()}
console.log('PASS: disjoint save preserves remote fields; same-field conflict; explicit latest choice; two-client cross-page presence; private topic; no email metadata; remote refresh deferral; local filters preserved; in-flight draft protection; disconnected status.');}finally{a.dom.window.close();b.dom.window.close()}})().catch(e=>{console.error(e);process.exitCode=1});
