const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),{JSDOM}=require('jsdom');
const html=fs.readFileSync('map-release/gi-map-v4.html','utf8'),main=fs.readFileSync('map-release/global-irradiance-analysis.html','utf8');
assert.equal(require('crypto').createHash('sha256').update(html.match(/<style>[\s\S]*?<\/style>/)[0]).digest('hex'),'9c422803a2a3d6e2b12c8a5cdff4625de1ed4d4633ac08a8ff096bd3f7fc7e41');
assert.ok(!html.includes('const GIMapDemoData='));
for(const text of [html,main])for(const m of text.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
for(const file of ['gi-map.js','gi-map-launcher.js','gi-map-v4-live.js'])new vm.Script(fs.readFileSync('map-release/'+file,'utf8'));
const dom=new JSDOM(html,{runScripts:'outside-only',url:'https://example.test/gi-map-v4.html'}),w=dom.window,ctx=dom.getInternalVMContext();
for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))vm.runInContext(m[1],ctx);
vm.runInContext(fs.readFileSync('map-release/gi-map-v4-live.js','utf8'),ctx);
const dates={'2026-09-01':5,'2026-09-02':null};
const p=(id,lat,v)=>({id,name:id,lat,lng:100,meta:{dates:{...dates,'2026-09-01':v}}});
const state={year:2026,month:8,rules:{radius:20,minPeers:3,method:'median'}},target=p('a',13,4),peers=[p('b',13.01,5),p('c',13.02,5),p('d',13.03,5)];
const result=w.GIMapLegacyCompare(target,state,[target,...peers]);assert.equal(result.eligible,true);assert.ok(Math.abs(result.diff+20)<1e-8);assert.equal(result.peers.length,3);
assert.equal(w.GIMapLegacyCompare(target,state,[target,...peers.slice(0,2)]).eligible,false);
assert.equal(w.GIMapLegacyCompare(target,state,[target,p('b',13.01,5),p('c',13.01,5),p('d',13.01,5)]).eligible,false);
assert.equal(w.GIMapLegacyCompare(p('missing',13,null),state,peers).reason,'no-data');
assert.ok(main.includes('GIMapLauncher.open(this)'));assert.ok(!main.includes('<div id="mapTab"'));
assert.ok(html.includes('data-action="return-gi"'));
target.irradiance={'2026':{'09':4}};peers.forEach(q=>q.irradiance={'2026':{'09':5}});
const average=w.GIMapAverageCompare(target,state,[target,...peers]);assert.equal(average.eligible,true);assert.ok(Math.abs(average.diff+20)<1e-8);
peers.forEach(q=>q.meta.dates['2026-09-01']=10);
assert.ok(Math.abs(w.GIMapAverageCompare(target,state,[target,...peers]).diff+20)<1e-8);
assert.ok(html.includes('ดูค่าเดิม (วิธีเทียบวันเดียวกัน)'));assert.ok(html.includes('คู่มืออ่านค่าแสงและสถานะ'));assert.ok(Math.abs(w.GIMapLiveCompare(target,state,[target,...peers]).diff+20)<1e-8);
const zeroPeers=peers.map(q=>({...q,irradiance:{'2026':{'09':0}}}));assert.equal(w.GIMapAverageCompare(target,state,[target,...zeroPeers]).reason,'invalid-base');
const mixedPeers=peers.map((q,i)=>({...q,irradiance:{'2026':{'09':[4,5,9][i]}}}));assert.equal(w.GIMapAverageCompare(target,state,[target,...mixedPeers]).base,5);assert.equal(w.GIMapAverageCompare(target,{...state,rules:{...state.rules,method:'mean'}},[target,...mixedPeers]).base,6);
dom.window.close();console.log('PASS: original CSS preserved, no demo bootstrap, syntax, real-data same-day comparison, peer/site checks, missing GI, navigation wiring.');

